apiVersion: apps/v1
kind: Deployment
metadata:
  name: sma-modbus-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sma-modbus-exporter
  template:
    metadata:
      labels:
        app: sma-modbus-exporter
    spec:
      containers:
      - name: mbmd
        image: volkszaehler/mbmd:latest
        args:
          - "run"
          - "-a=192.168.1.16:502"
          - "-d=SUNS:1@192.168.1.16:502"
          - "--api"
          - "--port=8080"
        ports:
        - containerPort: 8080
