apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sma-modbus-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: sma-modbus-exporter
  endpoints:
    - port: http
      interval: 15s
